name: Sentry CLI integration test

description: |
  Action to test Sentry CLI integration & symbol upload.
  Executes the script at the given path after starting a dummy Sentry server that collects and logs requests.
  The script is given the server URL as a first argument. Server and script output are saved in `server-output.txt` and
  `script-output.txt` respectively.

inputs:
  script:
    description: Script to run.
    required: true
  server-output-expected:
    description: If given, the server-produced output must match the file at this path.
    required: false
    default: ''
  script-output-expected:
    description: If given, the script-produced output must match the file at this path.
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Run ${{ inputs.script }}
      id: run
      run: |
        directory=$(dirname '${{ inputs.script }}')
        echo "directory=$directory" >> $GITHUB_OUTPUT
        pwsh '${{ github.action_path }}/execute.ps1' -Script '${{ inputs.script }}' -OutputDirectory "$directory"
      shell: bash

    - name: Check script-output.txt
      run: git diff --no-index ${{ steps.run.outputs.directory }}/script-output.txt ${{ inputs.script-output-expected }}
      if: ${{ inputs.script-output-expected }}
      shell: bash

    - name: Check server-output.txt
      run: git diff --no-index ${{ steps.run.outputs.directory }}/server-output.txt ${{ inputs.server-output-expected }}
      if: ${{ inputs.server-output-expected }}
      shell: bash
