# This isn't a reusable workflow but an actual CI action for this repo itself - to test scripts.
name: Updater Script Tests

on:
  push:

jobs:
  test:
    name: ${{ matrix.host }}
    runs-on: ${{ matrix.host }}-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - ubuntu
          - macos
          - windows
    steps:
      - uses: actions/checkout@v3

      - name: Install make
        if: ${{ matrix.host == 'macos' }}
        run: |
          brew install make
          echo "$(brew --prefix)/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - run: make test
        working-directory: updater
