# This isn't a reusable workflow but an actual CI action for this repo itself - to test scripts.
name: Updater Script Tests

on:
  push:

jobs:
  test:
    name: ${{ matrix.host }}
    runs-on: ${{ matrix.host }}-latest
    strategy:
      fail-fast: false
      matrix:
        host:
          - ubuntu
          - macos
          - windows
    steps:
      - uses: actions/checkout@v3
      - run: make test
        working-directory: updater
