# This isn't a reusable workflow but an actual CI action for this repo itself - to test the workflows.
name: Updater Workflow Tests

on:
  push:

jobs:
  create-pr:
    uses: ./.github/workflows/updater.yml
    with:
      path: updater/tests/sentry-cli.properties
      name: CLI
      pattern: '^2\.0\.'
      pr-strategy: update
      _workflow_version: ${{ github.sha }}
    secrets:
      api-token: ${{ github.token }}

  test-args:
    uses: ./.github/workflows/updater.yml
    with:
      path: updater/tests/workflow-args.sh
      name: Workflow args test script
      runs-on: macos-latest
      pattern: '.*'
      _workflow_version: ${{ github.sha }}
    secrets:
      api-token: ${{ github.token }}

  test-outputs:
    runs-on: ubuntu-latest
    needs:
      - create-pr
      - test-args
    steps:
      - run: "[[ '${{ needs.create-pr.outputs.baseBranch }}' == 'main' ]]"
      - run: "[[ '${{ needs.create-pr.outputs.originalTag }}' == '2.0.0' ]]"
      - run: "[[ '${{ needs.create-pr.outputs.latestTag }}' =~ ^[0-9.]+$ ]]"
      - run: "[[ '${{ needs.create-pr.outputs.prUrl }}' =~ ^https://github.com/getsentry/github-workflows/pull/[0-9]+$ ]]"
      - run: "[[ '${{ needs.create-pr.outputs.prBranch }}' == 'deps/updater/tests/sentry-cli.properties' ]]"

      - run: "[[ '${{ needs.test-args.outputs.baseBranch }}' == '' ]]"
      - run: "[[ '${{ needs.test-args.outputs.originalTag }}' == 'latest' ]]"
      - run: "[[ '${{ needs.test-args.outputs.latestTag }}' == 'latest' ]]"
      - run: "[[ '${{ needs.test-args.outputs.prUrl }}' == '' ]]"
      - run: "[[ '${{ needs.test-args.outputs.prBranch }}' == '' ]]"
